[main]
rootpasswd = "admin"
ipaddr = "localhost"
port = "8000"
# appdir = "{{DIRS.JSAPPSDIR}}/portals/portalbase"
appdir = "{{DIRS.CODEDIR}}/github/threefoldtech/jumpscale_portal_classic/apps/portalbase"
filesroot = "{{DIRS.VARDIR}}/portal/files"
defaultspace = "system"
defaultpage = ""
admingroups = ["admin"]
authentication_method = "me"
contentdirs =  ""
production = false
public_url = ""
jwt = ""

# [portal.{name}.mongoengine]
# host = "localhost"
# port = 27017

[oauth]
force_oauth_instance = ""  # set to use oauth
client_url = "https://itsyou.online/v1/oauth/authorize"
token_url = "https://itsyou.online/v1/oauth/access_token"
redirect_url = "http://ae5d255c.ngrok.io/restmachine/system/oauth/authorize"
client_scope = "user:email:main,user:memberof:JSPortal"
client_id = "JSPortal"
client_secret = "8plUHNtpaQp8NExkRa-3MYa1SWkOr1mgEqRxGBm25DD78tHXiIlS"
client_user_info_url = "https://itsyou.online/api/users/"
client_logout_url = ""
organization =  "testOrg"
default_groups = ["admin", "user"]
